spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://localhost:5432/EngineeringWork?reWriteBatchedInserts=true
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          batch_size: 35
          batch_versioned_data: true
  liquibase:
    change-log: classpath:liquibase-changeLog.xml